export const WaetherApiCall = "https://api.openweathermap.org/data/2.5/weather?q="
export const ForecastApiCall = "https://api.openweathermap.org/data/2.5/forecast?q="
export const LocationApiCall = "https://api.bigdatacloud.net/data/reverse-geocode-client?"
export const Metric = "&units=metric"
export const ApiKey = "&appid=f816f1c7fc58061a8d4b99d210789fa3" 